package com.drd.malisisdoors.init;

import com.drd.malisisdoors.MalisisDoorsReopened;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Items;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class ModCreativeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, MalisisDoorsReopened.MOD_ID);

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MALISISDOORS_TAB = CREATIVE_TABS.register("malisisdoors_tab", () -> CreativeModeTab.builder()
            .title(Component.translatable("itemGroup.malisisdoors"))
            // TODO: Will be changed to the Iron Jail Door
            .icon(() -> Items.IRON_DOOR.getDefaultInstance())
            .displayItems((parameters, output) -> {
                output.accept(Items.OAK_DOOR);
                output.accept(Items.SPRUCE_DOOR);
                output.accept(Items.BIRCH_DOOR);
                output.accept(Items.JUNGLE_DOOR);
                output.accept(Items.ACACIA_DOOR);
                output.accept(Items.DARK_OAK_DOOR);
                output.accept(Items.MANGROVE_DOOR);
                output.accept(Items.CHERRY_DOOR);
                output.accept(Items.PALE_OAK_DOOR);
                output.accept(Items.BAMBOO_DOOR);
                output.accept(Items.CRIMSON_DOOR);
                output.accept(Items.WARPED_DOOR);
                output.accept(Items.IRON_DOOR);
                // output.accept(ModItems.RUSTY_IRON_DOOR.get());
                output.accept(Items.COPPER_DOOR);
                output.accept(Items.EXPOSED_COPPER_DOOR);
                output.accept(Items.WEATHERED_COPPER_DOOR);
                output.accept(Items.OXIDIZED_COPPER_DOOR);
                output.accept(Items.WAXED_COPPER_DOOR);
                output.accept(Items.WAXED_EXPOSED_COPPER_DOOR);
                output.accept(Items.WAXED_WEATHERED_COPPER_DOOR);
                output.accept(Items.WAXED_OXIDIZED_COPPER_DOOR);
                // output.accept(ModItems.OAK_GLASS_DOOR.get());
                // output.accept(ModItems.SPRUCE_GLASS_DOOR.get());
                // output.accept(ModItems.BIRCH_GLASS_DOOR.get());
                // output.accept(ModItems.JUNGLE_GLASS_DOOR.get());
                // output.accept(ModItems.ACACIA_GLASS_DOOR.get());
                // output.accept(ModItems.DARK_OAK_GLASS_DOOR.get());
                // output.accept(ModItems.MANGROVE_GLASS_DOOR.get());
                // output.accept(ModItems.CHERRY_GLASS_DOOR.get());
                // output.accept(ModItems.PALE_OAK_GLASS_DOOR.get());
                // output.accept(ModItems.BAMBOO_GLASS_DOOR.get());
                // output.accept(ModItems.CRIMSON_GLASS_DOOR.get());
                // output.accept(ModItems.WARPED_GLASS_DOOR.get());
                // output.accept(ModItems.IRON_GLASS_DOOR.get());
                // output.accept(ModItems.RUSTY_IRON_GLASS_DOOR.get());
                // output.accept(ModItems.COPPER_GLASS_DOOR.get());
                // output.accept(ModItems.EXPOSED_COPPER_GLASS_DOOR.get());
                // output.accept(ModItems.WEATHERED_COPPER_GLASS_DOOR.get());
                // output.accept(ModItems.OXIDIZED_COPPER_GLASS_DOOR.get());
                // output.accept(ModItems.WAXED_COPPER_GLASS_DOOR.get());
                // output.accept(ModItems.WAXED_EXPOSED_COPPER_GLASS_DOOR.get());
                // output.accept(ModItems.WAXED_WEATHERED_COPPER_GLASS_DOOR.get());
                // output.accept(ModItems.WAXED_OXIDIZED_COPPER_GLASS_DOOR.get());
                // output.accept(ModItems.IRON_JAIL_DOOR.get());
                // output.accept(ModItems.COPPER_JAIL_DOOR.get());
                // output.accept(ModItems.EXPOSED_COPPER_JAIL_DOOR.get());
                // output.accept(ModItems.WEATHERED_COPPER_JAIL_DOOR.get());
                // output.accept(ModItems.OXIDIZED_COPPER_JAIL_DOOR.get());
                // output.accept(ModItems.WAXED_COPPER_JAIL_DOOR.get());
                // output.accept(ModItems.WAXED_EXPOSED_COPPER_JAIL_DOOR.get());
                // output.accept(ModItems.WAXED_WEATHERED_COPPER_JAIL_DOOR.get());
                // output.accept(ModItems.WAXED_OXIDIZED_COPPER_JAIL_DOOR.get());
                // output.accept(ModItems.LABORATORY_DOOR.get());
                // output.accept(ModItems.FACTORY_DOOR.get());
                // output.accept(ModItems.OAK_SHOJI_DOOR.get());
                // output.accept(ModItems.SPRUCE_SHOJI_DOOR.get());
                // output.accept(ModItems.BIRCH_SHOJI_DOOR.get());
                // output.accept(ModItems.JUNGLE_SHOJI_DOOR.get());
                // output.accept(ModItems.ACACIA_SHOJI_DOOR.get());
                // output.accept(ModItems.DARK_OAK_SHOJI_DOOR.get());
                // output.accept(ModItems.MANGROVE_SHOJI_DOOR.get());
                // output.accept(ModItems.CHERRY_SHOJI_DOOR.get());
                // output.accept(ModItems.PALE_OAK_SHOJI_DOOR.get());
                // output.accept(ModItems.BAMBOO_SHOJI_DOOR.get());
                // output.accept(ModItems.CRIMSON_SHOJI_DOOR.get());
                // output.accept(ModItems.WARPED_SHOJI_DOOR.get());
                // output.accept(ModItems.WHITE_CURTAIN.get());
                // output.accept(ModItems.LIGHT_GRAY_CURTAIN.get());
                // output.accept(ModItems.GRAY_CURTAIN.get());
                // output.accept(ModItems.BLACK_CURTAIN.get());
                // output.accept(ModItems.BROWN_CURTAIN.get());
                // output.accept(ModItems.RED_CURTAIN.get());
                // output.accept(ModItems.ORANGE_CURTAIN.get());
                // output.accept(ModItems.YELLOW_CURTAIN.get());
                // output.accept(ModItems.LIME_CURTAIN.get());
                // output.accept(ModItems.GREEN_CURTAIN.get());
                // output.accept(ModItems.CYAN_CURTAIN.get());
                // output.accept(ModItems.LIGHT_BLUE_CURTAIN.get());
                // output.accept(ModItems.BLUE_CURTAIN.get());
                // output.accept(ModItems.PURPLE_CURTAIN.get());
                // output.accept(ModItems.MAGENTA_CURTAIN.get());
                // output.accept(ModItems.PINK_CURTAIN.get());
                // output.accept(ModItems.OAK_SALOON_DOOR.get());
                // output.accept(ModItems.SPRUCE_SALOON_DOOR.get());
                // output.accept(ModItems.BIRCH_SALOON_DOOR.get());
                // output.accept(ModItems.JUNGLE_SALOON_DOOR.get());
                // output.accept(ModItems.ACACIA_SALOON_DOOR.get());
                // output.accept(ModItems.DARK_OAK_SALOON_DOOR.get());
                // output.accept(ModItems.MANGROVE_SALOON_DOOR.get());
                // output.accept(ModItems.CHERRY_SALOON_DOOR.get());
                // output.accept(ModItems.PALE_OAK_SALOON_DOOR.get());
                // output.accept(ModItems.BAMBOO_SALOON_DOOR.get());
                // output.accept(ModItems.CRIMSON_SALOON_DOOR.get());
                // output.accept(ModItems.WARPED_SALOON_DOOR.get());
                output.accept(Items.OAK_TRAPDOOR);
                output.accept(Items.SPRUCE_TRAPDOOR);
                output.accept(Items.BIRCH_TRAPDOOR);
                output.accept(Items.JUNGLE_TRAPDOOR);
                output.accept(Items.ACACIA_TRAPDOOR);
                output.accept(Items.DARK_OAK_TRAPDOOR);
                output.accept(Items.MANGROVE_TRAPDOOR);
                output.accept(Items.CHERRY_TRAPDOOR);
                output.accept(Items.PALE_OAK_TRAPDOOR);
                output.accept(Items.BAMBOO_TRAPDOOR);
                output.accept(Items.CRIMSON_TRAPDOOR);
                output.accept(Items.WARPED_TRAPDOOR);
                output.accept(Items.IRON_TRAPDOOR);
                // output.accept(ModItems.RUSTY_IRON_TRAPDOOR.get());
                output.accept(Items.COPPER_TRAPDOOR);
                output.accept(Items.EXPOSED_COPPER_TRAPDOOR);
                output.accept(Items.WEATHERED_COPPER_TRAPDOOR);
                output.accept(Items.OXIDIZED_COPPER_TRAPDOOR);
                output.accept(Items.WAXED_COPPER_TRAPDOOR);
                output.accept(Items.WAXED_EXPOSED_COPPER_TRAPDOOR);
                output.accept(Items.WAXED_WEATHERED_COPPER_TRAPDOOR);
                output.accept(Items.WAXED_OXIDIZED_COPPER_TRAPDOOR);
                // output.accept(ModItems.SLIDING_TRAPDOOR.get());
                output.accept(Items.OAK_FENCE_GATE);
                output.accept(Items.SPRUCE_FENCE_GATE);
                output.accept(Items.BIRCH_FENCE_GATE);
                output.accept(Items.JUNGLE_FENCE_GATE);
                output.accept(Items.ACACIA_FENCE_GATE);
                output.accept(Items.DARK_OAK_FENCE_GATE);
                output.accept(Items.MANGROVE_FENCE_GATE);
                output.accept(Items.CHERRY_FENCE_GATE);
                output.accept(Items.PALE_OAK_FENCE_GATE);
                output.accept(Items.BAMBOO_FENCE_GATE);
                output.accept(Items.CRIMSON_FENCE_GATE);
                output.accept(Items.WARPED_FENCE_GATE);
                // output.accept(ModItems.CAMO_FENCE_GATE.get());
                // output.accept(ModItems.REINFORCED_DOOR.get());
                // output.accept(ModItems.OAK_GARAGE_DOOR.get());
                // output.accept(ModItems.SPRUCE_GARAGE_DOOR.get());
                // output.accept(ModItems.BIRCH_GARAGE_DOOR.get());
                // output.accept(ModItems.JUNGLE_GARAGE_DOOR.get());
                // output.accept(ModItems.ACACIA_GARAGE_DOOR.get());
                // output.accept(ModItems.DARK_OAK_GARAGE_DOOR.get());
                // output.accept(ModItems.MANGROVE_GARAGE_DOOR.get());
                // output.accept(ModItems.CHERRY_GARAGE_DOOR.get());
                // output.accept(ModItems.PALE_OAK_GARAGE_DOOR.get());
                // output.accept(ModItems.BAMBOO_GARAGE_DOOR.get());
                // output.accept(ModItems.CRIMSON_GARAGE_DOOR.get());
                // output.accept(ModItems.WARPED_GARAGE_DOOR.get());
                // output.accept(ModItems.OAK_CARRIAGE_DOOR.get());
                // output.accept(ModItems.SPRUCE_CARRIAGE_DOOR.get());
                // output.accept(ModItems.BIRCH_CARRIAGE_DOOR.get());
                // output.accept(ModItems.JUNGLE_CARRIAGE_DOOR.get());
                // output.accept(ModItems.ACACIA_CARRIAGE_DOOR.get());
                // output.accept(ModItems.DARK_OAK_CARRIAGE_DOOR.get());
                // output.accept(ModItems.MANGROVE_CARRIAGE_DOOR.get());
                // output.accept(ModItems.CHERRY_CARRIAGE_DOOR.get());
                // output.accept(ModItems.PALE_OAK_CARRIAGE_DOOR.get());
                // output.accept(ModItems.BAMBOO_CARRIAGE_DOOR.get());
                // output.accept(ModItems.CRIMSON_CARRIAGE_DOOR.get());
                // output.accept(ModItems.WARPED_CARRIAGE_DOOR.get());
                // output.accept(ModItems.OAK_MEDIEVAL_DOOR.get());
                // output.accept(ModItems.SPRUCE_MEDIEVAL_DOOR.get());
                // output.accept(ModItems.BIRCH_MEDIEVAL_DOOR.get());
                // output.accept(ModItems.JUNGLE_MEDIEVAL_DOOR.get());
                // output.accept(ModItems.ACACIA_MEDIEVAL_DOOR.get());
                // output.accept(ModItems.DARK_OAK_MEDIEVAL_DOOR.get());
                // output.accept(ModItems.MANGROVE_MEDIEVAL_DOOR.get());
                // output.accept(ModItems.CHERRY_MEDIEVAL_DOOR.get());
                // output.accept(ModItems.PALE_OAK_MEDIEVAL_DOOR.get());
                // output.accept(ModItems.BAMBOO_MEDIEVAL_DOOR.get());
                // output.accept(ModItems.CRIMSON_MEDIEVAL_DOOR.get());
                // output.accept(ModItems.WARPED_MEDIEVAL_DOOR.get());
                // output.accept(ModItems.LARGE_OAK_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_SPRUCE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BIRCH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_JUNGLE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_ACACIA_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_DARK_OAK_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_MANGROVE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CHERRY_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_PALE_OAK_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BAMBOO_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CRIMSON_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WARPED_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_IRON_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_RUSTY_IRON_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_COPPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_EXPOSED_COPPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WEATHERED_COPPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_OXIDIZED_COPPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WAXED_COPPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WAXED_EXPOSED_COPPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WAXED_WEATHERED_COPPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WAXED_OXIDIZED_COPPER_DOOR_3X3.get());
                // output.accept(ModItems.RUSTY_HATCH.get());
                // output.accept(ModItems.RUSTY_HANDLE.get());
                // output.accept(ModItems.RUSTY_LADDER.get());
                // output.accept(ModItems.DOOR_FACTORY.get());
                // output.accept(ModItems.FORCEFIELD_CONTROLLER.get());
                // output.accept(ModItems.HITECH_DOOR.get());
            }).build());

    public static void register(IEventBus eventBus) {
        CREATIVE_TABS.register(eventBus);
    }
}
