package com.drd.malisisdoors.compat.mcwdoors;

import com.drd.malisisdoors.MalisisDoorsReopened;
import com.mcwdoors.kikoz.init.ItemInit;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class MacawsDoorsCreativeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, MalisisDoorsReopened.MOD_ID);

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MALISISDOORS_MACAWS_TAB = CREATIVE_TABS.register("malisisdoors_macaws_tab", () -> CreativeModeTab.builder()
            .title(Component.translatable("itemGroup.malisisdoors.macawsdoors"))
            // TODO: Will be changed to the Large Oak Cottage Double Doors
            .icon(() -> ItemInit.OAK_COTTAGE_DOOR.get().getDefaultInstance())
            .displayItems((parameters, output) -> {
                output.accept(ItemInit.SPRUCE_CLASSIC_DOOR.get());
                output.accept(ItemInit.BIRCH_CLASSIC_DOOR.get());
                output.accept(ItemInit.JUNGLE_CLASSIC_DOOR.get());
                output.accept(ItemInit.ACACIA_CLASSIC_DOOR.get());
                output.accept(ItemInit.DARK_OAK_CLASSIC_DOOR.get());
                output.accept(ItemInit.MANGROVE_CLASSIC_DOOR.get());
                output.accept(ItemInit.CHERRY_CLASSIC_DOOR.get());
                output.accept(ItemInit.PALE_OAK_CLASSIC_DOOR.get());
                output.accept(ItemInit.BAMBOO_CLASSIC_DOOR.get());
                output.accept(ItemInit.CRIMSON_CLASSIC_DOOR.get());
                output.accept(ItemInit.WARPED_CLASSIC_DOOR.get());
                output.accept(ItemInit.OAK_COTTAGE_DOOR.get());
                output.accept(ItemInit.BIRCH_COTTAGE_DOOR.get());
                output.accept(ItemInit.JUNGLE_COTTAGE_DOOR.get());
                output.accept(ItemInit.ACACIA_COTTAGE_DOOR.get());
                output.accept(ItemInit.DARK_OAK_COTTAGE_DOOR.get());
                output.accept(ItemInit.MANGROVE_COTTAGE_DOOR.get());
                output.accept(ItemInit.CHERRY_COTTAGE_DOOR.get());
                output.accept(ItemInit.PALE_OAK_COTTAGE_DOOR.get());
                output.accept(ItemInit.BAMBOO_COTTAGE_DOOR.get());
                output.accept(ItemInit.CRIMSON_COTTAGE_DOOR.get());
                output.accept(ItemInit.WARPED_COTTAGE_DOOR.get());
                output.accept(ItemInit.OAK_PAPER_DOOR.get());
                output.accept(ItemInit.SPRUCE_PAPER_DOOR.get());
                output.accept(ItemInit.JUNGLE_PAPER_DOOR.get());
                output.accept(ItemInit.ACACIA_PAPER_DOOR.get());
                output.accept(ItemInit.DARK_OAK_PAPER_DOOR.get());
                output.accept(ItemInit.MANGROVE_PAPER_DOOR.get());
                output.accept(ItemInit.CHERRY_PAPER_DOOR.get());
                output.accept(ItemInit.PALE_OAK_PAPER_DOOR.get());
                output.accept(ItemInit.BAMBOO_PAPER_DOOR.get());
                output.accept(ItemInit.CRIMSON_PAPER_DOOR.get());
                output.accept(ItemInit.WARPED_PAPER_DOOR.get());
                output.accept(ItemInit.OAK_BEACH_DOOR.get());
                output.accept(ItemInit.SPRUCE_BEACH_DOOR.get());
                output.accept(ItemInit.BIRCH_BEACH_DOOR.get());
                output.accept(ItemInit.ACACIA_BEACH_DOOR.get());
                output.accept(ItemInit.DARK_OAK_BEACH_DOOR.get());
                output.accept(ItemInit.MANGROVE_BEACH_DOOR.get());
                output.accept(ItemInit.CHERRY_BEACH_DOOR.get());
                output.accept(ItemInit.PALE_OAK_BEACH_DOOR.get());
                output.accept(ItemInit.BAMBOO_BEACH_DOOR.get());
                output.accept(ItemInit.CRIMSON_BEACH_DOOR.get());
                output.accept(ItemInit.WARPED_BEACH_DOOR.get());
                output.accept(ItemInit.OAK_TROPICAL_DOOR.get());
                output.accept(ItemInit.SPRUCE_TROPICAL_DOOR.get());
                output.accept(ItemInit.BIRCH_TROPICAL_DOOR.get());
                output.accept(ItemInit.JUNGLE_TROPICAL_DOOR.get());
                output.accept(ItemInit.DARK_OAK_TROPICAL_DOOR.get());
                output.accept(ItemInit.MANGROVE_TROPICAL_DOOR.get());
                output.accept(ItemInit.CHERRY_TROPICAL_DOOR.get());
                output.accept(ItemInit.PALE_OAK_TROPICAL_DOOR.get());
                output.accept(ItemInit.BAMBOO_TROPICAL_DOOR.get());
                output.accept(ItemInit.CRIMSON_TROPICAL_DOOR.get());
                output.accept(ItemInit.WARPED_TROPICAL_DOOR.get());
                output.accept(ItemInit.OAK_FOUR_PANEL_DOOR.get());
                output.accept(ItemInit.SPRUCE_FOUR_PANEL_DOOR.get());
                output.accept(ItemInit.BIRCH_FOUR_PANEL_DOOR.get());
                output.accept(ItemInit.JUNGLE_FOUR_PANEL_DOOR.get());
                output.accept(ItemInit.ACACIA_FOUR_PANEL_DOOR.get());
                output.accept(ItemInit.MANGROVE_FOUR_PANEL_DOOR.get());
                output.accept(ItemInit.CHERRY_FOUR_PANEL_DOOR.get());
                output.accept(ItemInit.PALE_OAK_FOUR_PANEL_DOOR.get());
                output.accept(ItemInit.BAMBOO_FOUR_PANEL_DOOR.get());
                output.accept(ItemInit.CRIMSON_FOUR_PANEL_DOOR.get());
                output.accept(ItemInit.WARPED_FOUR_PANEL_DOOR.get());
                output.accept(ItemInit.OAK_SWAMP_DOOR.get());
                output.accept(ItemInit.SPRUCE_SWAMP_DOOR.get());
                output.accept(ItemInit.BIRCH_SWAMP_DOOR.get());
                output.accept(ItemInit.JUNGLE_SWAMP_DOOR.get());
                output.accept(ItemInit.ACACIA_SWAMP_DOOR.get());
                output.accept(ItemInit.DARK_OAK_SWAMP_DOOR.get());
                output.accept(ItemInit.CHERRY_SWAMP_DOOR.get());
                output.accept(ItemInit.PALE_OAK_SWAMP_DOOR.get());
                output.accept(ItemInit.BAMBOO_SWAMP_DOOR.get());
                output.accept(ItemInit.CRIMSON_SWAMP_DOOR.get());
                output.accept(ItemInit.WARPED_SWAMP_DOOR.get());
                output.accept(ItemInit.OAK_WAFFLE_DOOR.get());
                output.accept(ItemInit.SPRUCE_WAFFLE_DOOR.get());
                output.accept(ItemInit.BIRCH_WAFFLE_DOOR.get());
                output.accept(ItemInit.JUNGLE_WAFFLE_DOOR.get());
                output.accept(ItemInit.ACACIA_WAFFLE_DOOR.get());
                output.accept(ItemInit.DARK_OAK_WAFFLE_DOOR.get());
                output.accept(ItemInit.MANGROVE_WAFFLE_DOOR.get());
                output.accept(ItemInit.PALE_OAK_WAFFLE_DOOR.get());
                output.accept(ItemInit.BAMBOO_WAFFLE_DOOR.get());
                output.accept(ItemInit.CRIMSON_WAFFLE_DOOR.get());
                output.accept(ItemInit.WARPED_WAFFLE_DOOR.get());
                output.accept(ItemInit.OAK_WHISPERING_DOOR.get());
                output.accept(ItemInit.SPRUCE_WHISPERING_DOOR.get());
                output.accept(ItemInit.BIRCH_WHISPERING_DOOR.get());
                output.accept(ItemInit.JUNGLE_WHISPERING_DOOR.get());
                output.accept(ItemInit.ACACIA_WHISPERING_DOOR.get());
                output.accept(ItemInit.DARK_OAK_WHISPERING_DOOR.get());
                output.accept(ItemInit.MANGROVE_WHISPERING_DOOR.get());
                output.accept(ItemInit.CHERRY_WHISPERING_DOOR.get());
                output.accept(ItemInit.BAMBOO_WHISPERING_DOOR.get());
                output.accept(ItemInit.CRIMSON_WHISPERING_DOOR.get());
                output.accept(ItemInit.WARPED_WHISPERING_DOOR.get());
                output.accept(ItemInit.OAK_BAMBOO_DOOR.get());
                output.accept(ItemInit.SPRUCE_BAMBOO_DOOR.get());
                output.accept(ItemInit.BIRCH_BAMBOO_DOOR.get());
                output.accept(ItemInit.JUNGLE_BAMBOO_DOOR.get());
                output.accept(ItemInit.ACACIA_BAMBOO_DOOR.get());
                output.accept(ItemInit.DARK_OAK_BAMBOO_DOOR.get());
                output.accept(ItemInit.MANGROVE_BAMBOO_DOOR.get());
                output.accept(ItemInit.CHERRY_BAMBOO_DOOR.get());
                output.accept(ItemInit.PALE_OAK_BAMBOO_DOOR.get());
                output.accept(ItemInit.CRIMSON_BAMBOO_DOOR.get());
                output.accept(ItemInit.WARPED_BAMBOO_DOOR.get());
                output.accept(ItemInit.OAK_NETHER_DOOR.get());
                output.accept(ItemInit.SPRUCE_NETHER_DOOR.get());
                output.accept(ItemInit.BIRCH_NETHER_DOOR.get());
                output.accept(ItemInit.JUNGLE_NETHER_DOOR.get());
                output.accept(ItemInit.ACACIA_NETHER_DOOR.get());
                output.accept(ItemInit.DARK_OAK_NETHER_DOOR.get());
                output.accept(ItemInit.MANGROVE_NETHER_DOOR.get());
                output.accept(ItemInit.CHERRY_NETHER_DOOR.get());
                output.accept(ItemInit.PALE_OAK_NETHER_DOOR.get());
                output.accept(ItemInit.BAMBOO_NETHER_DOOR.get());
                output.accept(ItemInit.WARPED_NETHER_DOOR.get());
                output.accept(ItemInit.OAK_MYSTIC_DOOR.get());
                output.accept(ItemInit.SPRUCE_MYSTIC_DOOR.get());
                output.accept(ItemInit.BIRCH_MYSTIC_DOOR.get());
                output.accept(ItemInit.JUNGLE_MYSTIC_DOOR.get());
                output.accept(ItemInit.ACACIA_MYSTIC_DOOR.get());
                output.accept(ItemInit.DARK_OAK_MYSTIC_DOOR.get());
                output.accept(ItemInit.MANGROVE_MYSTIC_DOOR.get());
                output.accept(ItemInit.CHERRY_MYSTIC_DOOR.get());
                output.accept(ItemInit.PALE_OAK_MYSTIC_DOOR.get());
                output.accept(ItemInit.BAMBOO_MYSTIC_DOOR.get());
                output.accept(ItemInit.CRIMSON_MYSTIC_DOOR.get());
                // output.accept(ModItems.LARGE_SPRUCE_CLASSIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BIRCH_CLASSIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_JUNGLE_CLASSIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_ACACIA_CLASSIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_DARK_OAK_CLASSIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_MANGROVE_CLASSIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CHERRY_CLASSIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_PALE_OAK_CLASSIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BAMBOO_CLASSIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CRIMSON_CLASSIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WARPED_CLASSIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_OAK_COTTAGE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BIRCH_COTTAGE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_JUNGLE_COTTAGE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_ACACIA_COTTAGE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_DARK_OAK_COTTAGE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_MANGROVE_COTTAGE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CHERRY_COTTAGE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_PALE_OAK_COTTAGE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BAMBOO_COTTAGE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CRIMSON_COTTAGE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WARPED_COTTAGE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_OAK_PAPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_SPRUCE_PAPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_JUNGLE_PAPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_ACACIA_PAPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_DARK_OAK_PAPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_MANGROVE_PAPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CHERRY_PAPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_PALE_OAK_PAPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BAMBOO_PAPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CRIMSON_PAPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WARPED_PAPER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_OAK_BEACH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_SPRUCE_BEACH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BIRCH_BEACH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_ACACIA_BEACH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_DARK_OAK_BEACH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_MANGROVE_BEACH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CHERRY_BEACH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_PALE_OAK_BEACH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BAMBOO_BEACH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CRIMSON_BEACH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WARPED_BEACH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_OAK_TROPICAL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_SPRUCE_TROPICAL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BIRCH_TROPICAL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_JUNGLE_TROPICAL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_DARK_OAK_TROPICAL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_MANGROVE_TROPICAL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CHERRY_TROPICAL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_PALE_OAK_TROPICAL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BAMBOO_TROPICAL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CRIMSON_TROPICAL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WARPED_TROPICAL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_OAK_NINE_PANEL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_SPRUCE_NINE_PANEL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BIRCH_NINE_PANEL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_JUNGLE_NINE_PANEL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_ACACIA_NINE_PANEL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_MANGROVE_NINE_PANEL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CHERRY_NINE_PANEL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_PALE_OAK_NINE_PANEL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BAMBOO_NINE_PANEL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CRIMSON_NINE_PANEL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WARPED_NINE_PANEL_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_OAK_SWAMP_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_SPRUCE_SWAMP_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BIRCH_SWAMP_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_JUNGLE_SWAMP_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_ACACIA_SWAMP_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_DARK_OAK_SWAMP_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CHERRY_SWAMP_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_PALE_OAK_SWAMP_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BAMBOO_SWAMP_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CRIMSON_SWAMP_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WARPED_SWAMP_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_OAK_WAFFLE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_SPRUCE_WAFFLE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BIRCH_WAFFLE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_JUNGLE_WAFFLE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_ACACIA_WAFFLE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_DARK_OAK_WAFFLE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_MANGROVE_WAFFLE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_PALE_OAK_WAFFLE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BAMBOO_WAFFLE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CRIMSON_WAFFLE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WARPED_WAFFLE_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_OAK_WHISPERING_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_SPRUCE_WHISPERING_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BIRCH_WHISPERING_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_JUNGLE_WHISPERING_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_ACACIA_WHISPERING_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_DARK_OAK_WHISPERING_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_MANGROVE_WHISPERING_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CHERRY_WHISPERING_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BAMBOO_WHISPERING_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CRIMSON_WHISPERING_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WARPED_WHISPERING_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_OAK_MESH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_SPRUCE_MESH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BIRCH_MESH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_JUNGLE_MESH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_ACACIA_MESH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_DARK_OAK_MESH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_MANGROVE_MESH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CHERRY_MESH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_PALE_OAK_MESH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CRIMSON_MESH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WARPED_MESH_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_OAK_NETHER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_SPRUCE_NETHER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BIRCH_NETHER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_JUNGLE_NETHER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_ACACIA_NETHER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_DARK_OAK_NETHER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_MANGROVE_NETHER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CHERRY_NETHER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_PALE_OAK_NETHER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BAMBOO_NETHER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_WARPED_NETHER_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_OAK_MYSTIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_SPRUCE_MYSTIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BIRCH_MYSTIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_JUNGLE_MYSTIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_ACACIA_MYSTIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_DARK_OAK_MYSTIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_MANGROVE_MYSTIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CHERRY_MYSTIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_PALE_OAK_MYSTIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_BAMBOO_MYSTIC_DOOR_3X3.get());
                // output.accept(ModItems.LARGE_CRIMSON_MYSTIC_DOOR_3X3.get());
            }).build());

    public static void register(IEventBus eventBus) {
        CREATIVE_TABS.register(eventBus);
    }
}
