license="${mod_license}"
issueTrackerURL="https://github.com/DRD2k8/MalisisDoorsReopened/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

# Waiting until the mod is finished
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"

logoFile="logo.png"
credits="Ordinastie, for the original Malisis Doors"
authors="Dandi2k8"
description='''
The animated doors and custom doors are back!
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
